name: Net & Connect
on:
  push:
    branches:
      - development
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Next.js with SSH
      uses: appleboy/ssh-action@v1.0.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        #password: ${{ secrets.PASSWORD }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          set e
          cd /staging/net-and-connect
          git fetch && git reset --hard HEAD && git pull
          source ~/.nvm/nvm.sh
          nvm install 20
          nvm use 20
          npm i
          npm run build
          pm2 restart 13 --update-env
